### ISSUE TITLE
Fix browse back

### ISSUE THREAD

**Issue by fawind** [hpi-swa-teaching/Algernon-Launcher-old#44]
Display the last Algerterms when leaving the childList view by using `push` and `pop` on the `searchStack` (`ALGCore>>showChildList | showParentList`).

**Comment by koogle** [comment]
somebody did this already :)

**Comment by janukobytsch** [comment]
I had already implemented keeping track of the history in a <code>searchStack</code> as a starting point for this feature. However, there are still some issues with the status quo. Firstly, items that show up by default, i.e. for empty strings, are hidden when browsing back. Secondly, the cursor is still pointing at the first index of the search string. This will result in adding characters to the beginning of the search string if you start typing after browsing back. I believe that the cursor in the input field should no longer be hidden since we will be using tab + shift tab for browsing between hierarchies instead of arrow keys (since there is no more action submenu). Could you look into this?
