### ISSUE TITLE
Finding the method "step" is not possible

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-teaching/Algernon-Launcher-old#60]
Again I start from a blank Algernon:

``` Smalltalk
ALGItemProvider initializeItems.
ALGCore initializeAlgernon.
```

If I search for the method "step", only classes are shown.

**Comment by janukobytsch** [comment]
Finding methods by searching on the topmost hierarchy level is in fact not possible by design. So in the given case you'd first search for "Morph", browse into the class, and subsequently search for "step", which will find the step-method as intended. This restriction has been made consciously with performance and usability in mind, but remains open for discussion of course.

**Comment by codeZeilen** [comment]
Ahh :)

I think that's fine, but it should probably be mentioned in the Readme. Vivide does also not allow a gobal Class and Method search. This might not be an issue for novice Squeak developers anyway, as they are not used to the global search yet.
